name: CI Checks
env:
  bashPass:   \033[32;1mPASSED -
  bashInfo:   \033[33;1mINFO -
  bashFail:   \033[31;1mFAILED -
  bashEnd:    \033[0m

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run spellings check
        uses: FreeRTOS/CI-CD-Github-Actions/spellings@main

  link-verifier:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3

      - name: Link Verification
        uses: FreeRTOS/CI-CD-Github-Actions/link-verifier@main

  formatting:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3

      - name: Check Formatting
        uses: FreeRTOS/CI-CD-Github-Actions/formatting@main
